export type PromoState = {
  id: string;
  shortId: string;
  merchantId: string;
  merchantLogo: string;
  background: string;
  titleRow1: string;
  titleRow2: string;
  titleBold: number;
  color: string;
  isHot: boolean;
  showBorder: boolean;
  cardLogo: string;
  isLoved: boolean;
  createdDate: string;
  startDate: string;
  endDate: string;
  locationName: string;
  distance: string;
  merchantPopularityRank: number;
  totalLovers: number;
  showCard: boolean;
  merchantCategory: string[];
  tags: string[];
  additionalTags?: string[];
  validDay?: string | null;
  validDate?: string | null;
  merchantName: string;
  isHidden: boolean;
};
